# Recipe API Configuration Template
# This configuration enables integration with external recipe APIs
# to enhance your meal planning with real recipes based on your meal database ingredients

recipe_integration:
  # Enable/disable recipe fetching
  enable_recipes: true

  # What percentage of meal options should be recipes vs component-based meals
  # 0.3 = 30% recipes, 70% component meals
  recipe_ratio: 0.3

  # Maximum number of recipes to show per meal type
  max_recipes_per_meal: 2

  # Recipe API configurations (get free API keys from these services)
  recipe_apis:
    # TheMealDB - Completely free, no API key required
    # Use test key '1' for all endpoints
    themealdb:
      enabled: true
      # No API key needed for TheMealDB

    # Edamam Recipe Search API - Free tier available
    # Sign up at: https://developer.edamam.com/
    edamam:
      enabled: false  # Set to true when you have API credentials
      app_id: "YOUR_EDAMAM_APP_ID"
      app_key: "YOUR_EDAMAM_APP_KEY"

    # Spoonacular Food API - Free tier available
    # Sign up at: https://spoonacular.com/food-api
    spoonacular:
      enabled: false  # Set to true when you have API credentials
      api_key: "YOUR_SPOONACULAR_API_KEY"

  # Dietary filters to apply when searching for recipes
  # These will be used to filter recipes from APIs that support it
  dietary_filters:
    - "high-protein"      # Focus on high-protein recipes
    # - "low-carb"        # Uncomment for low-carb focus
    # - "vegetarian"      # Uncomment for vegetarian recipes
    # - "vegan"           # Uncomment for vegan recipes
    # - "gluten-free"     # Uncomment for gluten-free recipes
    # - "dairy-free"      # Uncomment for dairy-free recipes
    # - "keto"            # Uncomment for ketogenic recipes
    # - "paleo"           # Uncomment for paleo recipes
    # - "low-fat"         # Uncomment for low-fat recipes
    # - "balanced"        # Uncomment for balanced nutrition

  # Recipe preferences
  preferences:
    # Preferred difficulty levels (easy, medium, hard)
    difficulty_preference: ["easy", "medium"]

    # Maximum cooking time (minutes) - recipes longer than this may be filtered out
    max_cook_time: 45

    # Minimum rating (if available from API) - 1-5 scale
    min_rating: 3.5

  # Cache settings
  cache:
    # How long to cache recipe results (seconds)
    cache_duration: 3600  # 1 hour

    # Maximum number of recipes to cache per meal type
    max_cache_size: 50

# Integration with existing meal database
meal_database_integration:
  # How to match ingredients between your database and recipe APIs
  ingredient_matching:
    # Use fuzzy matching to find similar ingredients
    use_fuzzy_matching: true

    # Minimum similarity score for ingredient matching (0.0-1.0)
    similarity_threshold: 0.7

  # Component prioritization when searching for recipes
  component_priority:
    proteins: 3    # Highest priority - recipes must include proteins
    vegetables: 2  # Medium priority - vegetables preferred
    carbs: 1       # Lower priority - carbs are optional
    fruits: 1      # Lower priority - fruits are optional

# Recipe display and formatting
display_settings:
  # How to format recipe instructions in calendar events
  instruction_preview_length: 200  # Characters

  # How to format ingredient lists in calendar events
  ingredient_display_limit: 8  # Maximum ingredients to show

  # Show cooking difficulty in calendar events
  show_difficulty: true

  # Show estimated prep/cook times
  show_timing: true

  # Show recipe source/URL
  show_source: true

# Example usage instructions:
# 1. Get a free TheMealDB account (no API key needed) - works immediately
# 2. Optional: Sign up for Edamam or Spoonacular free tier for more recipes
# 3. Update your main config file to include:
#    recipe_config: "./configs/recipe_config.yml"
# 4. Run your meal plan generator as usual - recipes will be automatically included!